package dev.selene.wallet.core

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Byte-exact vectors generated by @solana/web3.js 1.99 + @solana/spl-token 0.4.15
 * (see temp/sol-ref/refgen2.js). Fixed inputs:
 *   payer      = EtUqvMWtWDJqDjyoA7udffsK6N54vej836HZKcduFgkQ
 *   recipient  = 8Hqvts2uZBc8uRRECHbhje3qD6RYdBfeUTHQq7Q3Pzvn
 *   mint       = USDC (EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v)
 *   blockhash  = 11111111111111111111111111111111 (32 zero bytes)
 */
class TransactionBuilderTest {

    private val payer = "EtUqvMWtWDJqDjyoA7udffsK6N54vej836HZKcduFgkQ"
    private val recipient = "8Hqvts2uZBc8uRRECHbhje3qD6RYdBfeUTHQq7Q3Pzvn"
    private val mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
    private val blockhash = ByteArray(32)

    // ATA per @solana/spl-token getAssociatedTokenAddressSync
    private val sourceAta = "5rwQfh1tLMFUSgQXaujiKp4X4beJZZ3JfEnsdBK2NV2i"
    private val destAta = "BWtpPvvyzLR8wNbwf8kzrSacSJGuansn476mC9dGmJAv"

    private fun hex(s: String): ByteArray {
        require(s.length % 2 == 0) { "odd hex" }
        return ByteArray(s.length / 2) { i -> s.substring(2 * i, 2 * i + 2).toInt(16).toByte() }
    }

    private fun msgHex(raw: ByteArray): String =
        raw.joinToString("") { "%02x".format(it.toInt() and 0xff) }

    @Test
    fun base58RoundTrip() {
        val vectors = listOf(
            ByteArray(0) to "",
            byteArrayOf(0) to "1",
            byteArrayOf(0, 0, 0, 0) to "1111",
            byteArrayOf(0, 1) to "12",
            byteArrayOf(1) to "2",
            Base58.decodeToByteArray(payer) to payer,
            Base58.decodeToByteArray("BWtpPvvyzLR8wNbwf8kzrSacSJGuansn476mC9dGmJAv") to "BWtpPvvyzLR8wNbwf8kzrSacSJGuansn476mC9dGmJAv",
            hex("c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d61") to "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            hex("06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9") to "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            hex("8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859") to "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        )
        for ((bytes, expected) in vectors) {
            assertEquals(expected, Base58.encodeToString(bytes))
            assertArrayEquals(bytes, Base58.decodeToByteArray(expected))
        }
    }

    @Test
    fun solTransferMatchesWeb3() {
        val message = TransactionBuilder.solTransfer(
            from = Base58.decodeToByteArray(payer),
            to = Base58.decodeToByteArray(recipient),
            lamports = 1,
            recentBlockhash = blockhash
        )
        val expected = "01000103" +
            "ce5808b39c1dd34426ba2cfb647a2f9fd4e7c1e21df37fe3b9a550c9f9d65601" +
            "6c526d0569eb444f163ec438dfb10fabdd199dc481451dfa8b200d98923308a3" +
            "0000000000000000000000000000000000000000000000000000000000000000" +
            "0000000000000000000000000000000000000000000000000000000000000000" +
            "01020200010c020000000100000000000000"
        assertEquals(expected, msgHex(message))
    }

    @Test
    fun splTransferMatchesWeb3() {
        val message = TransactionBuilder.splTransfer(
            fromOwner = Base58.decodeToByteArray(payer),
            fromTokenAccount = Base58.decodeToByteArray(sourceAta),
            toTokenAccount = Base58.decodeToByteArray(destAta),
            amount = 1,
            recentBlockhash = blockhash
        )
        val expected = "01000104" +
            "ce5808b39c1dd34426ba2cfb647a2f9fd4e7c1e21df37fe3b9a550c9f9d65601" +
            "4839ba0b15475c174dbc4445409c84042e5d8db25faa64a67673dff8ea02586b" +
            "9c3d4d75b83c085d81ac3cbf88c93eca610b48fe911aefb3cad241ace9684273" +
            "06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9" +
            "0000000000000000000000000000000000000000000000000000000000000000" +
            "01030301020009030100000000000000"
        assertEquals(expected, msgHex(message))
    }

    @Test
    fun ataDerivationMatchesWeb3() {
        assertArrayEquals(Base58.decodeToByteArray(sourceAta), AssociatedToken.deriveAta(Base58.decodeToByteArray(mint), Base58.decodeToByteArray(payer)))
        assertArrayEquals(Base58.decodeToByteArray(destAta), AssociatedToken.deriveAta(Base58.decodeToByteArray(mint), Base58.decodeToByteArray(recipient)))
    }

    @Test
    fun combinedCreateAndTransferMessageStructurallyValid() {
        val message = TransactionBuilder.splTransferCreate(
            feePayer = Base58.decodeToByteArray(payer),
            fromTokenAccount = Base58.decodeToByteArray(sourceAta),
            toOwner = Base58.decodeToByteArray(recipient),
            mint = Base58.decodeToByteArray(mint),
            amount = 1,
            recentBlockhash = blockhash
        )
        val p = MessageParser(message)

        assertEquals(1, p.numRequiredSignatures)
        assertEquals(0, p.numReadonlySignedAccounts)
        assertEquals(5, p.numReadonlyUnsignedAccounts)
        assertEquals(8, p.keyCount)

assertEquals(payer, Base58.encodeToString(p.key(0)))       // fee payer: writable + signer
        assertEquals(sourceAta, Base58.encodeToString(p.key(1)))   // source ATA (writable)
        assertEquals(destAta, Base58.encodeToString(p.key(2)))     // recipient ATA (writable)
        assertEquals("11111111111111111111111111111111", Base58.encodeToString(p.key(3)))
        assertEquals(recipient, Base58.encodeToString(p.key(4)))   // recipient wallet (readonly)
        assertEquals("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", Base58.encodeToString(p.key(5)))
        assertEquals("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", Base58.encodeToString(p.key(6)))
        assertEquals("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", Base58.encodeToString(p.key(7)))

        assertEquals(2, p.instructionCount)

        // instruction 0: ATA create on the ATA program: [funder, ata, owner, mint, system, token]
        val create = p.instruction(0)
        assertEquals("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", Base58.encodeToString(p.key(create.programIdIndex)))
        assertArrayEquals(intArrayOf(0, 2, 4, 6, 3, 7), create.accountIndexes)
        assertEquals("", msgHex(create.data))

        // instruction 1: SPL transfer on the Token program: [source, ata, owner]
        val transfer = p.instruction(1)
        assertEquals("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", Base58.encodeToString(p.key(transfer.programIdIndex)))
        assertArrayEquals(intArrayOf(1, 2, 0), transfer.accountIndexes)
assertEquals("030100000000000000", msgHex(transfer.data))
    }

    @Test
    fun combinedCreateAndTransferMessageMatchesWeb3ByteExact() {
        val message = TransactionBuilder.splTransferCreate(
            feePayer = Base58.decodeToByteArray(payer),
            fromTokenAccount = Base58.decodeToByteArray(sourceAta),
            toOwner = Base58.decodeToByteArray(recipient),
            mint = Base58.decodeToByteArray(mint),
            amount = 1,
            recentBlockhash = blockhash
        )
        val expected = "01000508" +
            "ce5808b39c1dd34426ba2cfb647a2f9fd4e7c1e21df37fe3b9a550c9f9d65601" +
            "4839ba0b15475c174dbc4445409c84042e5d8db25faa64a67673dff8ea02586b" +
            "9c3d4d75b83c085d81ac3cbf88c93eca610b48fe911aefb3cad241ace9684273" +
            "0000000000000000000000000000000000000000000000000000000000000000" +
            "6c526d0569eb444f163ec438dfb10fabdd199dc481451dfa8b200d98923308a3" +
            "8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859" +
            "c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d61" +
            "06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9" +
            "0000000000000000000000000000000000000000000000000000000000000000" +
            "02050600020406030700070301020009030100000000000000"
        assertEquals(expected, msgHex(message))
    }

    @Test
    fun ed25519OnCurveKnownValues() {
        // web3 public keys (Keypair-generated) are on curve
        assertTrue(Ed25519.isOnCurve(Base58.decodeToByteArray(payer)))
        assertTrue(Ed25519.isOnCurve(Base58.decodeToByteArray(recipient)))
        // deriveAtas are PDAs and must be off curve
        assertTrue(!Ed25519.isOnCurve(Base58.decodeToByteArray(sourceAta)))
        assertTrue(!Ed25519.isOnCurve(Base58.decodeToByteArray(destAta)))
    }

    @Test
    fun wrapUnsignedTransactionEnvelope() {
        val message = TransactionBuilder.solTransfer(
            from = Base58.decodeToByteArray(payer),
            to = Base58.decodeToByteArray(recipient),
            lamports = 1,
            recentBlockhash = blockhash
        )
        val tx = wrapUnsignedTransaction(message, numSigners = 1)
        assertEquals(1 + 64 + message.size, tx.size)
        assertEquals(1, tx[0].toInt())
        for (i in 1 until 65) assertEquals(0, tx[i].toInt())
        val tail = tx.copyOfRange(65, tx.size)
        assertArrayEquals(message, tail)
    }
}

class MessageParser(private val bytes: ByteArray) {
    private var pos = 0

    val numRequiredSignatures: Int get() { pos = 0; return readU8() }
    val numReadonlySignedAccounts: Int get() { val h = header(); return h.second }
    val numReadonlyUnsignedAccounts: Int get() { val h = header(); return h.third }
    val keyCount: Int get() { val h = header(); skipKeys(h); return h.keyCount }
    val instructionCount: Int get() {
        val h = header(); skipKeys(h); return readShortVec()
    }

    private data class Header(val keyCount: Int, val second: Int, val third: Int)

    private var keysStart = 0

    private fun header(): Header {
        pos = 0
        readU8()
        val second = readU8()
        val third = readU8()
        val kc = readShortVec()
        keysStart = pos
        return Header(kc, second, third)
    }

    private fun skipKeys(h: Header) {
        pos = keysStart + h.keyCount * 32 + 32 // keys + blockhash
    }

    fun key(i: Int): ByteArray {
        header()
        pos = keysStart + i * 32
        return bytes.copyOfRange(pos, pos + 32)
    }

    fun instruction(i: Int): Instruction {
        val h = header(); skipKeys(h)
        val count = readShortVec()
        require(i < count) { "instruction index out of range" }
        repeat(i) {
            readU8()
            val n = readShortVec()
            repeat(n) { readU8() }
            val d = readShortVec()
            pos += d
        }
        val programIdIndex = readU8()
        val n = readShortVec()
        val accountIndexes = IntArray(n) { readU8() }
        val dLen = readShortVec()
        val data = bytes.copyOfRange(pos, pos + dLen)
        pos += dLen
        return Instruction(programIdIndex, accountIndexes, data)
    }

    private fun readU8(): Int = bytes[pos++].toInt() and 0xff

    private fun readShortVec(): Int {
        var result = 0
        var shift = 0
        while (true) {
            val byte = readU8()
            result = result or (byte and 0x7f shl shift)
            if (byte and 0x80 == 0) return result
            shift += 7
        }
    }
}

class Instruction(val programIdIndex: Int, val accountIndexes: IntArray, val data: ByteArray)
